version: "3.9"

networks:
  app-network:

services:

  redis:
    image: redis
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    networks:
      - app-network

  app:
    build: app
    command: gunicorn app:app -w 4 --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level info
    volumes:
      - ./app:/app
    environment:
      - DB_URI=postgresql+psycopg2://user:password@db:5432/app
      - BROKER_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - app-network

  worker:
    build: app
    command: celery -A celery_jobs worker --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - DB_URI=postgresql+psycopg2://user:password@db:5432/app
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - app-network