version: "3.9"

services:
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
  app:
    build: app
    command: gunicorn app:app -w 4 --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    environment:
      - DB_URI=postgresql+psycopg2://user:password@db:5432/app
      - BROKER_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  worker:
    build: app
    command: celery -A celery_jobs worker --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - DB_URI=postgresql+psycopg2://user:password@db:5432/app
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
