version: "3.9"

networks:
  app-network:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ../apm/prometheus/prometheus-entrega2.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network
    depends_on:
      - celery-metrics

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ../apm/grafana/config.ini:/etc/grafana/grafana.ini
      - ../apm/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ../apm/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ../apm/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

  celery-metrics:
    image: danihodovic/celery-exporter
    environment:
      - CE_BROKER_URL=redis://10.128.0.4:6379/0
    networks:
      - app-network