runtime: python310
instance_class: F1
service_account: entrega-5@aplicaciones-en-la-nube-382813.iam.gserviceaccount.com
entrypoint: gunicorn app:app -w 4 --access-logfile - --error-logfile - --log-level info
env_variables:
  PROJECT_ID: "aplicaciones-en-la-nube-382813"
automatic_scaling:
  max_instances: 1