global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: [ '10.128.0.8' ]

  - job_name: 'celery-metrics'
    static_configs:
      - targets: [ 'celery-metrics:9808' ]
