global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: [ '35.238.201.139' ]

  - job_name: 'celery-metrics'
    static_configs:
      - targets: [ '35.238.201.139:9000' ]
