global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: [ 'app:8000' ]

  - job_name: 'worker'
    static_configs:
      - targets: [ 'celery-metrics:9808' ]